version: 2.1

executors:
  my-executor:
    machine: true
    working_directory: ~/ci_app
    environment:
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

#general:
# Uncomment the following to specify only a specific branch
#   branches:
#     only:
#       - dev # specific branch
#       - /dev-.*/ # or regexes
jobs:
  prepare_org:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            . ~/ci_app/scripts/install.sh
            . ~/ci_app/scripts/auth-dev-hub.sh
      - run:
          name: Setup Org
          command: |
            sfdx force:org:create -s -f ~/ci_app/config/project-scratch-def.json -a circle_build_$CIRCLE_BUILD_NUM --wait 10 -v hub
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
            MY_ENV_VAR="FOO"
            echo ${MY_ENV_VAR}
            sfdx force:org:list
      - run:
          name: Run Apex Tests
          command: |
            echo 'Running tests'
            mkdir -p ~/junit
            sfdx force:apex:test:run -c -d ~/junit -r junit --wait 5
      - store_test_results:
          path: ~/junit
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  Delete_Scratch_Org:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
            at: .
      - run:
          name: Prepare
          command: |
            sfdx
            #. ~/ci_app/scripts/install.sh
            #. ~/ci_app/scripts/auth-dev-hub.sh
      - run:
          name: Delete Useless Scratch Org
          command: |
            echo ${MY_ENV_VAR}
            sfdx force:org:list
            sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p
            sfdx force:org:list

### Uncomment the following if performing deployments
#deployment:
#  override:
#    - sfdx force:source:convert -r force-app -d testDeploy
#    - . cleanupDeploy.sh
#    - sfdx force:mdapi:deploy -d testDeploy/ -u deploy -w 2

workflows:
  version: 2.1
  my-workflow:
    jobs:
      - prepare_org
      #- Delete_Scratch_Org?:
      #    requires:
      #      - prepare_org
      #    type: approval
      - Delete_Scratch_Org:
          requires:
            - prepare_org